channels:
- conda-forge
dependencies:
- python=3.9.1
- pip<=24.3.1
- pip:
  - mlflow==2.19.0
  - astunparse==1.6.3
  - cloudpickle==2.0.0
  - defusedxml==0.7.1
  - matplotlib==3.9.4
  - numpy==1.26.4
  - nvidia-ml-py==12.560.30
  - pandas==1.3.4
  - torch==2.5.1
  - tqdm==4.62.3
name: mlflow-env
